all:
	python main.py --train_file ./data/train.txt \
        --dev_file ./data/dev.txt \
        --embedding_file ./embedding/glove.6B.100d.txt \
	--num_epoches 1000 \
	--pre_trained model.pkl.gz \
	--eval_iter 150 \
	--test_only y
